name: DataMiner CICD Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  CI:
    uses: SkylineCommunications/.github/workflows/Automation Master Workflow.yml@master

  # # Optional 0 or More CD Jobs as needed
  # CD:
  #   if: $GITHUB_REF_TYPE == 'tag'
  #   environment: production
  #   name: CD
  #   runs-on: ubuntu-latest
  #   needs: CI

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Skyline DataMiner Deploy Action
  #       uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1.0.3
  #       with:
  #         # Stage deploy
  #         stage: Deploy
  #         # The API-key generated in the DCP Admin app as authentication for a certain DataMiner System. E.g. g597e77412e34297b827c2570a8fa2bc
  #         api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
  #         # Id of the uploaded artifact
  #         artifact-id: ${{ needs.CI.outputs.artifact-id }}